### ISSUE TITLE
Can't trigger with temperature 

### ISSUE THREAD

**Issue by hbkmanbass** [hirosan18/homebridge-nature-remo-sensor#15]
Dear developper, 

I can't trigger anything with temperature even on Home app or Eve app even if the both app can read the temperature

What should I do ?

Thanks in advance,

**Comment by hirosan18** [comment]
This plugin only provides temperature, humidity and illumination to Homekit through Homebridge. So, this does not support triggers.
Also, the Home app should not be able to create automation triggered by sensors.
If you tried to create a sensor-triggered automation in the Eve app and it didn't work, please contact Eve.

I created and tested a sensor-triggered automation in the Evo App, and the automation worked, so there may be problems with your configuration in Eve app .

Sorry, this is not the plugin's problem and the Issue is closed.
